package com.mast.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Assignment")
public class Assignment {
    
    private String assignmentId;
    private String studentId;
    private String assignmentTitle;
    private String assignmentContent;
    private Double grade;
    private String fileId;
    private String classId;
    
    
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getAssignmentId() {
        return assignmentId;
    }
    
    @DynamoDBAttribute
    public String getStudentId() {
        return studentId;
    }
    
    @DynamoDBAttribute
    public String getAssignmentContent() {
        return assignmentContent;
    }
    
    @DynamoDBAttribute
    public Double getGrade() {
        return grade;
    }
    @DynamoDBAttribute
    public String getFileId() {
        return fileId;
    }
    
    @DynamoDBAttribute
    public String getClassId() {
        return classId;
    }
    
    @DynamoDBAttribute
    public String getAssignmentTitle() {
        return assignmentTitle;
    }
    
    
}
