package com.mast.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Assignment")
public class Assignment {
    
    private Long assignmentId;
    private String assignmentTitle;
    private String assignmentContent;
    private Double grade;
    private Long fileId;
    private Long classId;
    
    // public User (Long userId, String firstName, String accountName, String lastName, String email, UserType userType) {
    //     this.userId = userId;
    //     this.firstName = firstName;
    //     this.lastName = lastName;
    //     this.email = email;
    // }
    
    
    
    @DynamoDBHashKey
    public Long getAssignmentId() {
        return userId;
    }
    @DynamoDBAttribute
    public String getFirstName() {
        return firstName;
    }
    
    @DynamoDBAttribute
    public String getAccountName() {
        return accountName;
    }
    @DynamoDBAttribute
    public String getLastName() {
        return lastName;
    }
    
    @DynamoDBAttribute
    public String getEmail() {
        return email;
    }
    
    @DynamoDBAttribute
    public String getUserType() {
        return userType;
    }
    
    
}
