package com.mast.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Grade")
public class Grade {
    
    private String gradeId;
    private String classId;
    private String studentId;
    private String assignmentId;
    private String createDate;
    
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getUserId() {
        return gradeId;
    }
    @DynamoDBAttribute
    public String getClassId() {
        return classId;
    }
    @DynamoDBAttribute
    public String getStudentId() {
        return studentId;
    }
    @DynamoDBAttribute
    public String getAssignmentId() {
        return assignmentId;
    }
    
    @DynamoDBAttribute
    public String getAccountName() {
        return createDate;
    }
    
    

}
