package com.mast.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "File")
public class Module {
    
    private String fileId;
    private String moduleId;
    private String classId;
    private String fileUrl;
    private String createDate;
    
    
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getModuleId() {
        return moduleId;
    }
    
    @DynamoDBAttribute
    public String getFileId() {
        return fileId;
    }
    @DynamoDBAttribute
    public String getClassId() {
        return classId;
    }
    @DynamoDBAttribute
    public String getFirstName() {
        return fileUrl;
    }
    
    @DynamoDBAttribute
    public String getAccountName() {
        return createDate;
    }
    
    

}
